FROM node:16-alpine as builder
ARG environment
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm ci --production
COPY . .
RUN npm run build:user
RUN npm run build:frontoffice

FROM node:16-alpine
WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/package.json /usr/src/app/package.json
COPY --from=builder /usr/src/app/dist /usr/src/app/dist
EXPOSE 4000
CMD ["npm", "run", "serve:frontoffice"]
